name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Nightly and rustfmt
        run: |
          rustup toolchain install nightly --profile minimal
          rustup component add rustfmt
      - name: Cache
        uses: actions/cache@v4
        with: # https://doc.rust-lang.org/cargo/guide/cargo-home.html
          path: |
            $CARGO_HOME/.crates.toml
            $CARGO_HOME/.crates2.json
            $CARGO_HOME/bin
            $CARGO_HOME/registry/index
            $CARGO_HOME/registry/cache
            $CARGO_HOME/git/db
            ~/.cache/cargo-xwin
            target/
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Add x86_64-pc-windows-msvc Target
        run: rustup target add x86_64-pc-windows-msvc
      - name: Install cargo-xwin
        run: cargo install --locked cargo-xwin
      - name: Check formatting
        run: cargo fmt --check
      - name: Build
        run: cargo heph --target-dir ./output/ -t hfw
